//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace storingVedios2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blob
    {
        public int ID { get; set; }
        public string Path { get; set; }
        public string Name { get; set; }
        public int CourseID { get; set; }
        public byte[] FilePath { get; set; }
        public string FileName { get; set; }
    
        public virtual Cours Cours { get; set; }
    }
}
